import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Menu, Search, ThumbsUp, MessageSquare, Clock } from "lucide-react";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { useNavigate, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { useState } from "react";

const faqItems = [
  {
    q: "What file formats does FrameIQ support?",
    a: "FrameIQ supports MP4, MOV, AVI, and WebM for video analysis. You can also paste links from YouTube, TikTok, Meta Ads Library, and most ad spy tools.",
  },
  {
    q: "How does the AI video analysis work?",
    a: "When you upload a video, our AI extracts the hook (first 3 seconds), transcribes the full audio, identifies the creative model (UGC, talking head, product demo, etc.), and generates a production-ready brief — all in under 60 seconds.",
  },
  {
    q: "Can I analyze competitor ads from the Meta Ads Library?",
    a: "Yes! Just paste the ad URL and FrameIQ will download, analyze, and extract the creative structure, hook, CTA pattern, and more. Works with Meta, TikTok Creative Center, and YouTube ads.",
  },
  {
    q: "What is a 'Board' in FrameIQ?",
    a: "A Board is a production-ready creative brief generated by AI. It includes scene breakdowns, voiceover scripts, editor notes, and visual references — everything your editor or agency needs to produce the ad.",
  },
  {
    q: "How many team seats are included in each plan?",
    a: "The Free plan includes 1 seat. Studio includes 1 seat. Scale includes up to 10 seats. Enterprise plans can accommodate unlimited seats.",
  },
  {
    q: "Does FrameIQ replace my creative agency?",
    a: "FrameIQ doesn't replace your creative team — it makes them faster. Your strategists spend less time on research and briefing, and more time on high-level creative decisions.",
  },
  {
    q: "Is my data secure?",
    a: "Yes. All data is encrypted at rest and in transit. We are SOC 2 compliant and never use your uploaded content to train our models. Your competitive insights stay private.",
  },
  {
    q: "Can I integrate FrameIQ with my existing tools?",
    a: "Scale and Enterprise plans include API access. You can integrate FrameIQ with Notion, Slack, Google Sheets, and your internal tools via our REST API and webhooks.",
  },
];

const communityPosts = [
  {
    title: "How I reduced ad production time from 3 days to 4 hours",
    author: "Sarah M.",
    role: "Creative Strategist at DTC Brand",
    time: "2 hours ago",
    likes: 24,
    replies: 8,
    tags: ["Workflow", "Case Study"],
  },
  {
    title: "Best practices for analyzing competitor hooks on TikTok",
    author: "James L.",
    role: "Performance Marketer",
    time: "5 hours ago",
    likes: 18,
    replies: 12,
    tags: ["TikTok", "Hooks"],
  },
  {
    title: "Using FrameIQ boards to brief freelance editors — my process",
    author: "Ana R.",
    role: "Head of Creative, Agency",
    time: "1 day ago",
    likes: 31,
    replies: 15,
    tags: ["Boards", "Agency"],
  },
  {
    title: "How to structure A/B tests with AI-generated creative variants",
    author: "Mike K.",
    role: "Growth Lead",
    time: "1 day ago",
    likes: 14,
    replies: 6,
    tags: ["Testing", "Strategy"],
  },
  {
    title: "Feature request: Bulk video analysis via CSV upload",
    author: "Priya S.",
    role: "Media Buyer",
    time: "2 days ago",
    likes: 42,
    replies: 19,
    tags: ["Feature Request"],
  },
];

const Community = () => {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState("");

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-border/50 bg-background/60 backdrop-blur-xl">
        <div className="container mx-auto flex items-center justify-between px-6 py-4">
          <Link to="/" className="text-2xl font-bold flex items-center">
            <span className="text-foreground font-medium">Frame</span>
            <span className="gradient-text font-black">IQ</span>
          </Link>
          <div className="hidden md:flex items-center gap-8">
            <Link to="/#features" className="text-sm text-secondary hover:text-foreground transition-colors">Features</Link>
            <Link to="/#pricing" className="text-sm text-secondary hover:text-foreground transition-colors">Pricing</Link>
            <Link to="/blog" className="text-sm text-secondary hover:text-foreground transition-colors">Blog</Link>
            <Link to="/community" className="text-sm text-foreground transition-colors">Community</Link>
            <Link to="/contact" className="text-sm text-secondary hover:text-foreground transition-colors">Contact</Link>
          </div>
          <div className="hidden md:flex items-center gap-3">
            <Button variant="ghost" className="text-secondary hover:text-foreground" onClick={() => navigate("/login")}>Sign in</Button>
            <Button className="bg-gradient-to-r from-purple-600 to-pink-600 text-white hover:from-purple-700 hover:to-pink-700 border-0" onClick={() => navigate("/signup")}>Get started free</Button>
          </div>
          <Sheet>
            <SheetTrigger asChild className="md:hidden">
              <Button variant="ghost" size="icon"><Menu className="h-6 w-6" /></Button>
            </SheetTrigger>
            <SheetContent>
              <div className="flex flex-col gap-6 mt-8">
                <Link to="/" className="text-lg text-secondary hover:text-foreground">Home</Link>
                <Link to="/blog" className="text-lg text-secondary hover:text-foreground">Blog</Link>
                <Link to="/community" className="text-lg text-foreground">Community</Link>
                <Link to="/contact" className="text-lg text-secondary hover:text-foreground">Contact</Link>
                <Button className="bg-gradient-to-r from-purple-600 to-pink-600 text-white" onClick={() => navigate("/signup")}>Get started</Button>
              </div>
            </SheetContent>
          </Sheet>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-12 px-6">
        <div className="container mx-auto max-w-4xl text-center">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <span className="text-sm font-semibold tracking-wider uppercase gradient-text">Community & Support</span>
            <h1 className="text-4xl md:text-5xl font-bold mt-4 mb-4">Get answers. Share knowledge.</h1>
            <p className="text-secondary text-lg max-w-2xl mx-auto">
              Browse FAQs, share workflows, and connect with other creative strategists and performance marketers using FrameIQ.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Search */}
      <section className="px-6 pb-8">
        <div className="container mx-auto max-w-2xl">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <Input
              placeholder="Search questions, topics, or keywords..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-12 h-12 rounded-xl bg-card/80 border-border/50"
            />
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="px-6 pb-16">
        <div className="container mx-auto max-w-3xl">
          <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
          <Accordion type="single" collapsible className="space-y-3">
            {faqItems
              .filter((item) =>
                searchQuery === "" ||
                item.q.toLowerCase().includes(searchQuery.toLowerCase()) ||
                item.a.toLowerCase().includes(searchQuery.toLowerCase())
              )
              .map((item, i) => (
                <AccordionItem
                  key={i}
                  value={`faq-${i}`}
                  className="rounded-xl px-5 border-border/50"
                  style={{ background: 'rgba(139, 92, 246, 0.03)', border: '1px solid rgba(139, 92, 246, 0.1)' }}
                >
                  <AccordionTrigger className="text-left text-[15px] font-medium hover:no-underline">
                    {item.q}
                  </AccordionTrigger>
                  <AccordionContent className="text-secondary leading-relaxed">
                    {item.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
          </Accordion>
        </div>
      </section>

      {/* Community Discussions */}
      <section className="px-6 pb-24">
        <div className="container mx-auto max-w-3xl">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold">Community Discussions</h2>
            <Button
              className="bg-gradient-to-r from-purple-600 to-pink-600 text-white border-0"
              onClick={() => navigate("/signup")}
            >
              Join to post
            </Button>
          </div>

          <div className="space-y-4">
            {communityPosts.map((post, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.05 }}
                className="p-5 rounded-xl cursor-pointer hover:border-purple-500/30 transition-all"
                style={{ background: 'rgba(139, 92, 246, 0.03)', border: '1px solid rgba(139, 92, 246, 0.1)' }}
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <h3 className="font-semibold mb-1 hover:text-purple-400 transition-colors">{post.title}</h3>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground mb-3">
                      <span className="font-medium text-foreground/70">{post.author}</span>
                      <span>·</span>
                      <span>{post.role}</span>
                      <span>·</span>
                      <Clock className="w-3 h-3" />
                      <span>{post.time}</span>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      {post.tags.map((tag) => (
                        <span
                          key={tag}
                          className="text-xs px-2.5 py-1 rounded-full"
                          style={{ background: 'rgba(139, 92, 246, 0.15)', color: '#a78bfa' }}
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground shrink-0">
                    <span className="flex items-center gap-1">
                      <ThumbsUp className="w-3.5 h-3.5" />
                      {post.likes}
                    </span>
                    <span className="flex items-center gap-1">
                      <MessageSquare className="w-3.5 h-3.5" />
                      {post.replies}
                    </span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default Community;
