import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Input } from "@/components/ui/input";
import { Menu, Search } from "lucide-react";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { useNavigate, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { useState } from "react";

const faqItems = [
  {
    q: "What file formats does FrameIQ support?",
    a: "FrameIQ supports MP4, MOV, AVI, and WebM for video analysis. You can also paste links from YouTube, TikTok, Meta Ads Library, and most ad spy tools.",
  },
  {
    q: "How does the AI video analysis work?",
    a: "When you upload a video, our AI extracts the hook (first 3 seconds), transcribes the full audio, identifies the creative model (UGC, talking head, product demo, etc.), and generates a production-ready brief — all in under 60 seconds.",
  },
  {
    q: "Can I analyze competitor ads from the Meta Ads Library?",
    a: "Yes! Just paste the ad URL and FrameIQ will download, analyze, and extract the creative structure, hook, CTA pattern, and more. Works with Meta, TikTok Creative Center, and YouTube ads.",
  },
  {
    q: "What is a 'Board' in FrameIQ?",
    a: "A Board is a production-ready creative brief generated by AI. It includes scene breakdowns, voiceover scripts, editor notes, and visual references — everything your editor or agency needs to produce the ad.",
  },
  {
    q: "How many team seats are included in each plan?",
    a: "The Free plan includes 1 seat. Studio includes 1 seat. Scale includes up to 10 seats. Enterprise plans can accommodate unlimited seats — contact us for details.",
  },
  {
    q: "Does FrameIQ replace my creative agency?",
    a: "FrameIQ doesn't replace your creative team — it makes them faster. Your strategists spend less time on research and briefing, and more time on high-level creative decisions.",
  },
  {
    q: "Is my data secure?",
    a: "Yes. All data is encrypted at rest and in transit. We are SOC 2 compliant and never use your uploaded content to train our models. Your competitive insights stay private.",
  },
  {
    q: "Can I integrate FrameIQ with my existing tools?",
    a: "Scale and Enterprise plans include API access. You can integrate FrameIQ with Notion, Slack, Google Sheets, and your internal tools via our REST API and webhooks.",
  },
  {
    q: "What AI models power FrameIQ?",
    a: "FrameIQ is powered by OpenAI and Anthropic models, combined with our proprietary creative intelligence engine trained on millions of ad performance patterns.",
  },
  {
    q: "Can I cancel my subscription at any time?",
    a: "Yes. You can cancel anytime from your dashboard. Your access continues until the end of your billing period. No cancellation fees.",
  },
  {
    q: "Do you offer a free trial?",
    a: "Yes! Our Free plan gives you 3 video analyses and 3 boards per month at no cost. Studio plans include a 14-day free trial with full features.",
  },
  {
    q: "What languages does Auto Translation support?",
    a: "FrameIQ supports 40+ languages including Portuguese, Spanish, French, German, Japanese, Korean, Arabic, and more. All translations are context-aware and preserve marketing intent.",
  },
];

const FAQ = () => {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState("");

  const filtered = faqItems.filter(
    (item) =>
      searchQuery === "" ||
      item.q.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.a.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-border/50 bg-background/60 backdrop-blur-xl">
        <div className="container mx-auto flex items-center justify-between px-6 py-4">
          <Link to="/" className="text-2xl font-bold flex items-center">
            <span className="text-foreground font-medium">Frame</span>
            <span className="gradient-text font-black">IQ</span>
          </Link>
          <div className="hidden md:flex items-center gap-8">
            <Link to="/#features" className="text-sm text-secondary hover:text-foreground transition-colors">Features</Link>
            <Link to="/#pricing" className="text-sm text-secondary hover:text-foreground transition-colors">Pricing</Link>
            <Link to="/blog" className="text-sm text-secondary hover:text-foreground transition-colors">Blog</Link>
            <Link to="/faq" className="text-sm text-foreground transition-colors">FAQ</Link>
            <Link to="/contact" className="text-sm text-secondary hover:text-foreground transition-colors">Contact</Link>
          </div>
          <div className="hidden md:flex items-center gap-3">
            <Button variant="ghost" className="text-secondary hover:text-foreground" onClick={() => navigate("/login")}>Sign in</Button>
            <Button className="bg-gradient-to-r from-purple-600 to-pink-600 text-white hover:from-purple-700 hover:to-pink-700 border-0" onClick={() => navigate("/signup")}>Get started free</Button>
          </div>
          <Sheet>
            <SheetTrigger asChild className="md:hidden">
              <Button variant="ghost" size="icon"><Menu className="h-6 w-6" /></Button>
            </SheetTrigger>
            <SheetContent>
              <div className="flex flex-col gap-6 mt-8">
                <Link to="/" className="text-lg text-secondary hover:text-foreground">Home</Link>
                <Link to="/blog" className="text-lg text-secondary hover:text-foreground">Blog</Link>
                <Link to="/faq" className="text-lg text-foreground">FAQ</Link>
                <Link to="/contact" className="text-lg text-secondary hover:text-foreground">Contact</Link>
                <Button className="bg-gradient-to-r from-purple-600 to-pink-600 text-white" onClick={() => navigate("/signup")}>Get started</Button>
              </div>
            </SheetContent>
          </Sheet>
        </div>
      </nav>

      <section className="pt-32 pb-12 px-6">
        <div className="container mx-auto max-w-3xl text-center">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <span className="text-sm font-semibold tracking-wider uppercase gradient-text">Support</span>
            <h1 className="text-4xl md:text-5xl font-bold mt-4 mb-4">Frequently Asked Questions</h1>
            <p className="text-secondary text-lg max-w-xl mx-auto">
              Everything you need to know about FrameIQ. Can't find what you're looking for? Contact us at support@frameiq.com.
            </p>
          </motion.div>
        </div>
      </section>

      <section className="px-6 pb-8">
        <div className="container mx-auto max-w-2xl">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <Input
              placeholder="Search questions..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-12 h-12 rounded-xl bg-card/80 border-border/50"
            />
          </div>
        </div>
      </section>

      <section className="px-6 pb-24">
        <div className="container mx-auto max-w-2xl">
          <Accordion type="single" collapsible className="space-y-3">
            {filtered.map((item, i) => (
              <AccordionItem
                key={i}
                value={`faq-${i}`}
                className="rounded-xl px-5 border-border/50"
                style={{ background: 'rgba(139, 92, 246, 0.03)', border: '1px solid rgba(139, 92, 246, 0.1)' }}
              >
                <AccordionTrigger className="text-left text-[15px] font-medium hover:no-underline">
                  {item.q}
                </AccordionTrigger>
                <AccordionContent className="text-secondary leading-relaxed">
                  {item.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>

          {filtered.length === 0 && (
            <p className="text-center text-muted-foreground py-12">No results found. Try a different search or contact support@frameiq.com.</p>
          )}
        </div>
      </section>
    </div>
  );
};

export default FAQ;
