-- ============================================================
-- FRAMEIQ SEO — SEED DATA (Phase 2)
-- Reference rows only. NOT production data.
-- Used to validate schema + test queries before Phase 3.
-- ============================================================

-- ── seo_tools (5 tools) ──────────────────────────────────────
insert into public.seo_tools (slug, name, description, long_description, meta_title, meta_description, keywords, tool_type, is_free, requires_auth, dashboard_route, published)
values
  ('ad-hook-generator',
   'Ad Hook Generator',
   'Generate 10 high-converting ad hooks for any product, platform, and market in seconds.',
   'Describe your product and audience, pick a tone and platform — FrameIQ AI generates 10 proven hook formulas with predicted scores, platform fit, and CTA suggestions.',
   'Free Ad Hook Generator — FrameIQ',
   'Generate high-converting ad hooks for TikTok, Facebook, and Instagram in seconds. Free AI-powered tool by FrameIQ.',
   array['ad hook generator', 'tiktok hook ideas', 'free ad hook generator', 'hook generator for ads'],
   'generator', true, false, '/dashboard/hooks', true),

  ('ad-script-generator',
   'Ad Script Generator',
   'Turn your product description into a full video ad script — hook, body, CTA.',
   'Input your product, target audience, and platform. FrameIQ builds a complete ad script in the proven Hook → Story → CTA structure — ready to brief your editor.',
   'Free Ad Script Generator — FrameIQ',
   'Generate complete video ad scripts for TikTok, Reels, and YouTube Shorts in seconds. Free tool by FrameIQ.',
   array['ad script generator', 'video script generator', 'tiktok script generator', 'free ad script'],
   'generator', true, true, '/dashboard/boards/new', true),

  ('ad-creative-analyzer',
   'Ad Creative Analyzer',
   'Upload any video ad and get an instant hook score, platform fit analysis, and improvement suggestions.',
   'Drop your video — FrameIQ transcribes, scores the hook (0–10), identifies the creative model, checks platform safety zones, and gives you 3 actionable improvements.',
   'Free Ad Creative Analyzer — Hook Score Tool | FrameIQ',
   'Analyze your video ad for hook strength, platform fit, and CTR potential. Free AI tool. Get your hook score in 60 seconds.',
   array['ad creative analyzer', 'hook score tool', 'video ad analyzer', 'tiktok ad analyzer'],
   'analyzer', true, true, '/dashboard/analyses/new', true),

  ('ctr-estimator',
   'CTR Estimator',
   'Estimate the click-through rate of your ad creative based on hook type, platform, and industry benchmarks.',
   'Input your hook type, platform, ad format, and industry — FrameIQ benchmarks it against our creative intelligence database to estimate expected CTR range and conversion signals.',
   'Ad CTR Estimator — Free Tool | FrameIQ',
   'Estimate your ad CTR before spending a dollar. Free benchmark tool based on 10k+ ad creatives. By FrameIQ.',
   array['ctr estimator', 'ad ctr calculator', 'tiktok ctr benchmark', 'facebook ad ctr'],
   'calculator', true, false, null, true),

  ('competitor-ad-decoder',
   'Competitor Ad Decoder',
   'Paste any competitor ad script and get the full creative framework, emotional triggers, and counter-strategy.',
   'Paste the script or transcript of any competitor ad. FrameIQ reverse-engineers the hook type, persuasion model, target audience, and gives you a counter-strategy in seconds.',
   'Competitor Ad Decoder — Free Tool | FrameIQ',
   'Reverse-engineer any competitor ad in seconds. Understand the hook, framework, and tactics — then build your counter-strategy. Free AI tool.',
   array['competitor ad analysis', 'decode competitor ad', 'ad framework analyzer', 'reverse engineer ad'],
   'analyzer', true, false, '/dashboard/competitor', true);

-- ── seo_comparisons (3 competitors) ─────────────────────────
insert into public.seo_comparisons (slug, competitor_name, competitor_slug, headline, summary, meta_title, meta_description, keywords, frameiq_price, competitor_price, frameiq_pros, competitor_pros, feature_table, published)
values
  ('frameiq-vs-adspy',
   'AdSpy',
   'adspy',
   'FrameIQ vs AdSpy — Which Ad Intelligence Tool Is Right for You?',
   'AdSpy is a Facebook/Instagram ad spy tool. FrameIQ is an AI-powered creative analyzer. If you want to spy on competitor ads, AdSpy wins on database size. If you want to understand WHY ads work and improve your own creatives, FrameIQ wins.',
   'FrameIQ vs AdSpy — Full Comparison 2025',
   'FrameIQ vs AdSpy: detailed comparison of features, pricing, and use cases. Which ad intelligence tool is right for your team?',
   array['frameiq vs adspy', 'adspy alternative', 'adspy competitor', 'best ad intelligence tool'],
   'From $19/mo',
   '$149/mo',
   array['AI hook scoring', 'Video analysis in 60s', 'Creative brief generation', 'Translation & transcription', 'Competitor pattern decoder'],
   array['Massive ad database', 'Facebook & Instagram coverage', 'Filter by engagement metrics'],
   '[{"feature":"AI hook scoring","frameiq":"✓","competitor":"✗"},{"feature":"Video upload analysis","frameiq":"✓","competitor":"✗"},{"feature":"Ad database browsing","frameiq":"✗","competitor":"✓"},{"feature":"Creative brief generator","frameiq":"✓","competitor":"✗"},{"feature":"Free plan","frameiq":"✓","competitor":"✗"},{"feature":"Monthly price","frameiq":"$19","competitor":"$149"}]'::jsonb,
   true),

  ('frameiq-vs-bigspy',
   'BigSpy',
   'bigspy',
   'FrameIQ vs BigSpy — Ad Spy Tool vs AI Creative Analyzer',
   'BigSpy is an ad spy tool covering multiple platforms. FrameIQ focuses on analyzing and improving YOUR ad creatives using AI. Different tools, different jobs.',
   'FrameIQ vs BigSpy — Full Comparison 2025',
   'FrameIQ vs BigSpy: compare features, pricing, and use cases. Find out which ad tool fits your workflow.',
   array['frameiq vs bigspy', 'bigspy alternative', 'bigspy vs frameiq'],
   'From $19/mo',
   'From $9/mo',
   array['AI creative analysis', 'Hook scoring', 'Script generation', 'Video transcription', 'Team collaboration'],
   array['Multi-platform ad library', 'Lower entry price', 'Filter by country & category'],
   '[{"feature":"AI hook scoring","frameiq":"✓","competitor":"✗"},{"feature":"Ad library browsing","frameiq":"✗","competitor":"✓"},{"feature":"Creative brief generator","frameiq":"✓","competitor":"✗"},{"feature":"Free plan","frameiq":"✓","competitor":"Limited"},{"feature":"Monthly price","frameiq":"$19","competitor":"$9"}]'::jsonb,
   true),

  ('frameiq-vs-minea',
   'Minea',
   'minea',
   'FrameIQ vs Minea — Creative Intelligence vs Product Research',
   'Minea is primarily a product research tool with ad browsing. FrameIQ is built for creative teams who need to analyze, score, and improve their own ad performance.',
   'FrameIQ vs Minea — Full Comparison 2025',
   'FrameIQ vs Minea: which tool is best for ad creative analysis? Full feature and pricing comparison.',
   array['frameiq vs minea', 'minea alternative', 'minea vs frameiq', 'minea competitor'],
   'From $19/mo',
   'From $49/mo',
   array['AI analysis in 60s', 'Hook score & benchmarks', 'Brief generation', 'Free plan available'],
   array['Product research features', 'Influencer discovery', 'Pinterest & TikTok coverage'],
   '[{"feature":"AI hook scoring","frameiq":"✓","competitor":"✗"},{"feature":"Product research","frameiq":"✗","competitor":"✓"},{"feature":"Creative brief generator","frameiq":"✓","competitor":"✗"},{"feature":"Free plan","frameiq":"✓","competitor":"✗"},{"feature":"Monthly price","frameiq":"$19","competitor":"$49"}]'::jsonb,
   true);

-- ── seo_landing_pages (6 keyword-driven pages) ───────────────
insert into public.seo_landing_pages (slug, title, headline, subheadline, body_intro, meta_title, meta_description, keywords, filter_platform, filter_industry, published)
values
  ('tiktok-ad-examples',
   'TikTok Ad Examples',
   'The Best TikTok Ad Examples — Analyzed',
   'See what makes top TikTok ads work. Hook score, creative framework, and breakdown for every ad.',
   'TikTok has become the most powerful platform for direct response advertising. But what separates a 9.1-scoring viral ad from a 4.2 that bleeds spend? In this library, every ad is scored for hook strength, creative model, and platform fit — so you can learn from what actually works.',
   'Best TikTok Ad Examples (Analyzed) — FrameIQ',
   'Browse the best TikTok ad examples with hook scores, creative breakdowns, and AI analysis. Updated weekly.',
   array['tiktok ad examples', 'best tiktok ads', 'tiktok ad examples 2025', 'tiktok advertising examples'],
   'tiktok', null, true),

  ('facebook-ad-examples',
   'Facebook Ad Examples',
   'High-Performing Facebook Ad Examples — With Analysis',
   'Real ads, real breakdowns. Understand the creative structure behind every top Facebook ad.',
   'Facebook remains the highest-volume platform for paid social. The best Facebook ads share a common pattern: a scroll-stopping hook in the first 3 seconds, a clear problem-solution arc, and a CTA that feels inevitable. Here''s the library — all scored, all analyzed.',
   'Best Facebook Ad Examples (Analyzed) — FrameIQ',
   'Browse top-performing Facebook ad examples with AI analysis, hook scores, and creative breakdowns.',
   array['facebook ad examples', 'best facebook ads', 'facebook advertising examples', 'facebook video ad examples'],
   'facebook', null, true),

  ('ugc-ad-examples',
   'UGC Ad Examples',
   'The Best UGC Ad Examples — What Makes Them Work',
   'User-generated content ads outperform polished creative by 4x on average. Here''s why.',
   'UGC ads consistently outperform studio-produced creative on TikTok, Reels, and Facebook. The reason is trust — audiences recognize authentic content and respond differently to it. This library collects the highest-scoring UGC ads across platforms, with full creative analysis.',
   'Best UGC Ad Examples (Analyzed) — FrameIQ',
   'Browse the best UGC ad examples with hook scores and creative analysis. See exactly why UGC ads convert.',
   array['ugc ad examples', 'ugc advertising examples', 'user generated content ads', 'ugc creative examples'],
   null, null, true),

  ('igaming-ad-examples',
   'iGaming Ad Examples',
   'Top iGaming & Betting Ad Examples — Creative Breakdown',
   'The highest-performing casino and sports betting ads — analyzed for hook, creative model, and compliance signals.',
   'iGaming advertising requires a specific creative playbook: urgency, social proof, and a hook that stands out in a saturated feed. This library focuses on high-performing creatives from BR, MX, and IN markets — the three highest-growth regulated markets right now.',
   'Best iGaming Ad Examples (Analyzed) — FrameIQ',
   'Browse top iGaming and betting ad examples with hook scores and creative analysis. Brazil, Mexico, India markets.',
   array['igaming ad examples', 'betting ad examples', 'casino ad examples', 'sports betting advertising'],
   null, 'igaming', true),

  ('ecommerce-ad-examples',
   'Ecommerce Ad Examples',
   'Top Ecommerce Ad Examples — Hook Scores & Breakdowns',
   'The creative formulas that drive DTC revenue. Every ad analyzed for hook, narrative, and CTA.',
   'Ecommerce advertising lives and dies by the first 3 seconds. The best DTC brands have mastered a tight creative formula: product in frame fast, problem acknowledged, social proof layered in, CTA before the skip. Here''s the library — all scored, all explained.',
   'Best Ecommerce Ad Examples (Analyzed) — FrameIQ',
   'Browse top ecommerce and DTC ad examples with AI analysis, hook scores, and creative breakdowns.',
   array['ecommerce ad examples', 'dtc ad examples', 'ecommerce advertising examples', 'shopify ad examples'],
   null, 'ecommerce', true),

  ('best-ad-hooks',
   'Best Ad Hooks',
   '50 Best Ad Hooks — Scored & Categorized',
   'The opening lines that stop the scroll. Organized by type, platform, and predicted performance.',
   'The hook is the single most important variable in any video ad. A 9.0-scoring hook on a mediocre ad will outperform a polished 30-second spot with a weak opener. This database collects the highest-performing hooks across platforms — curiosity gaps, social proof, pattern interrupts, and more.',
   'Best Ad Hooks (Scored & Categorized) — FrameIQ',
   'Browse 50+ high-performing ad hooks with hook scores and analysis. Organized by type, platform, and industry.',
   array['best ad hooks', 'tiktok ad hooks', 'facebook ad hooks', 'high converting ad hooks', 'ad hook examples'],
   null, null, true);

-- ── seo_content (guide cluster: TikTok Ads) ──────────────────
insert into public.seo_content (slug, section, cluster, title, subtitle, summary, meta_title, meta_description, keywords, read_time_min, related_slugs, cta_type, published)
values
  ('tiktok-ads-guide',
   'guides', 'tiktok-ads',
   'TikTok Ads: The Complete Guide for 2025',
   'Everything you need to know about TikTok advertising — from hook strategy to scaling.',
   'A complete, practical guide to TikTok advertising: creative formats, hook types, bidding strategy, and how to scale what works.',
   'TikTok Ads Guide 2025 — Complete Strategy | FrameIQ',
   'The complete guide to TikTok advertising in 2025. Hook strategy, creative formats, scaling playbook. By FrameIQ.',
   array['tiktok ads guide', 'tiktok advertising guide', 'how to advertise on tiktok', 'tiktok ads strategy'],
   12,
   array['tiktok-ad-hooks-guide', 'tiktok-ad-testing-guide', 'tiktok-ad-structure-guide'],
   'signup', true),

  ('tiktok-ad-hooks-guide',
   'guides', 'tiktok-ads',
   'TikTok Ad Hooks: 15 Proven Formulas That Stop the Scroll',
   'The exact hook structures that generate 8+ hook scores on TikTok — with examples.',
   'Learn the 15 hook formulas that consistently score 8+ on TikTok — with real examples and a breakdown of why each one works.',
   'Best TikTok Ad Hooks — 15 Proven Formulas | FrameIQ',
   '15 TikTok ad hook formulas that stop the scroll. With examples, hook scores, and breakdowns. Free guide by FrameIQ.',
   array['tiktok ad hooks', 'tiktok hook formulas', 'best tiktok hooks', 'tiktok ad opening lines'],
   8,
   array['tiktok-ads-guide', 'tiktok-ad-structure-guide', 'best-ad-hooks'],
   'tool', true),

  ('tiktok-ad-structure-guide',
   'guides', 'tiktok-ads',
   'TikTok Ad Structure: The Hook → Story → CTA Framework',
   'How to structure a TikTok ad that converts — from the first frame to the call to action.',
   'The proven 3-part structure behind every high-performing TikTok ad: Hook (0–3s), Story (3–20s), CTA (final 5s). With real examples.',
   'TikTok Ad Structure Guide — Hook → Story → CTA | FrameIQ',
   'How to structure a TikTok ad that converts. The proven Hook → Story → CTA framework with examples and analysis.',
   array['tiktok ad structure', 'tiktok ad framework', 'how to structure a tiktok ad', 'tiktok video ad structure'],
   7,
   array['tiktok-ads-guide', 'tiktok-ad-hooks-guide', 'tiktok-ad-testing-guide'],
   'signup', true),

  ('tiktok-ad-testing-guide',
   'guides', 'tiktok-ads',
   'TikTok Ad Testing: How to Find Your Winning Creative Fast',
   'A systematic approach to creative testing on TikTok — without burning budget.',
   'How to test TikTok ad creatives efficiently: what variables to isolate, how many variations to run, how to read early signals, and when to scale.',
   'TikTok Ad Testing Guide — Find Winning Creatives Fast | FrameIQ',
   'How to test TikTok ads and find winning creatives without wasting budget. Systematic creative testing playbook.',
   array['tiktok ad testing', 'tiktok creative testing', 'how to test tiktok ads', 'tiktok a/b testing ads'],
   9,
   array['tiktok-ads-guide', 'tiktok-ad-structure-guide', 'tiktok-ad-scaling-guide'],
   'signup', true),

  ('tiktok-ad-scaling-guide',
   'guides', 'tiktok-ads',
   'How to Scale TikTok Ads Without Creative Fatigue',
   'The scaling playbook for TikTok — how to increase spend while keeping ROAS stable.',
   'Scaling TikTok ads is a creative problem, not a budget problem. This guide covers horizontal scaling, creative refresh cadence, and how to spot fatigue before it kills your ROAS.',
   'How to Scale TikTok Ads — Scaling Playbook | FrameIQ',
   'How to scale TikTok ads without creative fatigue. The complete scaling playbook with budget strategy and refresh cadence.',
   array['scale tiktok ads', 'tiktok ads scaling', 'tiktok ad creative fatigue', 'how to scale tiktok advertising'],
   10,
   array['tiktok-ads-guide', 'tiktok-ad-testing-guide', 'tiktok-ad-hooks-guide'],
   'signup', true);
