-- Add action_recommendation and group_note to decisions table
-- These fields are generated by the decision engine (via Claude Haiku)
-- to provide specific next-step recommendations and group related decisions.

ALTER TABLE decisions ADD COLUMN IF NOT EXISTS action_recommendation TEXT;
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS group_note TEXT;
