// ── Design tokens ─────────────────────────────────────────────────────────────
export const FONTS = {
  sans:  "'Plus Jakarta Sans', sans-serif",
  body:  "'Plus Jakarta Sans', system-ui, sans-serif",
  mono:  "'DM Mono', monospace",
} as const;

export const COLORS = {
  accent:   "#0ea5e9",
  accentLo: "rgba(14,165,233,0.15)",
  accentMd: "rgba(14,165,233,0.30)",
  green:    "#34d399",
  red:      "#f87171",
  amber:    "#fbbf24",
  bg:       "#0c0f1a",
  surface:  "rgba(255,255,255,0.035)",
  border:   "rgba(255,255,255,0.07)",
  text:     "rgba(235,240,248,0.90)",
  textMid:  "rgba(255,255,255,0.45)",
  textLow:  "rgba(255,255,255,0.22)",
} as const;

// ── i18n strings ──────────────────────────────────────────────────────────────
export const T = {
  pt: {
    placeholder:      "Pergunte algo...",
    thinking:         "Pensando...",
    generatingHooks:  "Gerando hooks...",
    writingScript:    "Escrevendo roteiro...",
    checkingData:     "Verificando dados ao vivo...",
    analyzingPerf:    "Analisando performance...",
    readingCampaigns: "Lendo campanhas...",
    loadingCtx:       "Carregando contexto da conta, aguarde...",
    clearChat:        "Limpar conversa",
    clearConfirm:     "Limpar toda a conversa? Isso não pode ser desfeito.",
    copiar:           "Copiar",
    copiado:          "Copiado!",
    retry:            "Retry",
    live:             "ao vivo",
    updating:         "atualizando...",
    loading:          "carregando...",
    tryAgain:         "Tentar novamente",
    connectAccount:   "Conectar conta →",
    connectMeta:      "Conectar Meta Ads",
    connectGoogle:    "Ou conectar Google Ads →",
    createFirst:      "Criar conta primeiro →",
    connectsIn:       "Conectar leva menos de 2 minutos",
    noAdAccount:      "Conecte sua conta de anúncios",
    noAdAccountSub:   "Sem conexão, a IA responde de forma genérica. Com sua conta, ela vê CTR, spend, o que pausar e o que escalar.",
    seePlans:         "Ver planos →",
    weekSummary:      "Resumo da semana",
    whatToScale:      "O que escalar?",
    whatToPause:      "O que pausar?",
    nextCreative:     "Próximo criativo",
    whyDrop:          "Por que caiu?",
    scaleNow:         "▲ Escalar agora",
    fatigueRisk:      "▼ Risco de fadiga",
    topAds:           "Top anúncios",
    campaigns:        "Campanhas",
    aiLabel:          "AdBrief AI",
    errorConn:        "Erro de conexão",
    tokenExpired:     "Token expirado",
    tokenExpiredCta:  "reconecte em Contas →",
    noAccountSel:     "Nenhuma conta selecionada",
    noAccountSelCta:  "configure em Contas →",
    connectsWith:     "Conecta com",
    dashPlaceholder:  "Diga qual dashboard quer — campanhas, criativos, ROAS...",
  },
  es: {
    placeholder:      "Pregunta algo...",
    thinking:         "Pensando...",
    generatingHooks:  "Generando hooks...",
    writingScript:    "Escribiendo guión...",
    checkingData:     "Verificando datos en vivo...",
    analyzingPerf:    "Analizando rendimiento...",
    readingCampaigns: "Leyendo campañas...",
    loadingCtx:       "Cargando contexto de la cuenta...",
    clearChat:        "Limpiar chat",
    clearConfirm:     "¿Limpiar toda la conversación? Esto no se puede deshacer.",
    copiar:           "Copiar",
    copiado:          "¡Copiado!",
    retry:            "Retry",
    live:             "en vivo",
    updating:         "actualizando...",
    loading:          "cargando...",
    tryAgain:         "Reintentar",
    connectAccount:   "Conectar cuenta →",
    connectMeta:      "Conectar Meta Ads",
    connectGoogle:    "O conectar Google Ads →",
    createFirst:      "Crear cuenta primero →",
    connectsIn:       "Conectar toma menos de 2 minutos",
    noAdAccount:      "Conecta tu cuenta de anuncios",
    noAdAccountSub:   "Sin conexión la IA responde de forma genérica. Con tu cuenta ve CTR, spend, qué pausar y escalar.",
    seePlans:         "Ver planes →",
    weekSummary:      "Resumen semana",
    whatToScale:      "¿Qué escalar?",
    whatToPause:      "¿Qué pausar?",
    nextCreative:     "Próximo creativo",
    whyDrop:          "¿Por qué bajó?",
    scaleNow:         "▲ Escalar ahora",
    fatigueRisk:      "▼ Riesgo de fatiga",
    topAds:           "Top anuncios",
    campaigns:        "Campañas",
    aiLabel:          "AdBrief AI",
    errorConn:        "Error de conexión",
    tokenExpired:     "Token expirado",
    tokenExpiredCta:  "reconecta en Cuentas →",
    noAccountSel:     "Ninguna cuenta seleccionada",
    noAccountSelCta:  "configura en Cuentas →",
    connectsWith:     "Conecta con",
    dashPlaceholder:  "Di qué dashboard quieres — campañas, creativos, ROAS...",
  },
  en: {
    placeholder:      "Ask something...",
    thinking:         "Thinking...",
    generatingHooks:  "Generating hooks...",
    writingScript:    "Writing script...",
    checkingData:     "Checking live data...",
    analyzingPerf:    "Analyzing performance...",
    readingCampaigns: "Reading campaigns...",
    loadingCtx:       "Loading account context, just a moment...",
    clearChat:        "Clear chat",
    clearConfirm:     "Clear the entire conversation? This cannot be undone.",
    copiar:           "Copy",
    copiado:          "Copied!",
    retry:            "Retry",
    live:             "live",
    updating:         "updating...",
    loading:          "loading...",
    tryAgain:         "Retry",
    connectAccount:   "Connect account →",
    connectMeta:      "Connect Meta Ads",
    connectGoogle:    "Or connect Google Ads →",
    createFirst:      "Create account first →",
    connectsIn:       "Takes less than 2 minutes to connect",
    noAdAccount:      "Connect your ad account",
    noAdAccountSub:   "Without connection, AI gives generic answers. With your account it sees CTR, spend, what to pause and scale.",
    seePlans:         "See plans →",
    weekSummary:      "Week summary",
    whatToScale:      "What to scale?",
    whatToPause:      "What to pause?",
    nextCreative:     "Next creative",
    whyDrop:          "Why did it drop?",
    scaleNow:         "▲ Scale now",
    fatigueRisk:      "▼ Fatigue risk",
    topAds:           "Top ads",
    campaigns:        "Campaigns",
    aiLabel:          "AdBrief AI",
    errorConn:        "Connection error",
    tokenExpired:     "Token expired",
    tokenExpiredCta:  "reconnect in Accounts →",
    noAccountSel:     "No account selected",
    noAccountSelCta:  "configure in Accounts →",
    connectsWith:     "Connects with",
    dashPlaceholder:  "Say what dashboard you want — campaigns, creatives, ROAS...",
  },
} as const;

export type TKeys = keyof typeof T.pt;
